### ISSUE TITLE
Can't build on armv7 (Raspberry Pi, Go 1.11)

### ISSUE THREAD

**Issue by rcarmo** [candid82/joker#243]
```bash
pi@quad:~/Library/Go/src/github.com/candid82/joker $ ./run.sh --version 
# command-line-arguments
gen/gen_types.go:88:20: undefined: strings.ReplaceAll
core/object.go:2: running "go": exit status 2
```
I'm guessing this is because `ReplaceAll` seems to be in 1.12, just leaving this here because Raspbian `buster` is still shipping the older version. and someone else might search for this.

**Comment by rcarmo** [comment]
Upgrading to Go 1.12 I now get this when running `go install`:

```bash
# github.com/candid82/joker/std/time
std/time/a_time.go:13:24: constant 3600000000000 overflows int
std/time/a_time.go:17:26: constant 60000000000 overflows int
```

**Comment by candid82** [comment]
@rcarmo I updated Go version in build requirements. 
As for the second issue, 32-bit platforms are not officially supported. In hindsight I should have used `int64` instead of `int` to avoid issues like this, but oh well. If you are really interested in building Joker on a 32-bit platform, try commenting out the code that exposes those int vars in `time.joke`.
I'll see how much work it would be to migrate to `int64` everywhere, but that's definitely not a quick fix.

**Comment by jcburley** [comment]
Is this a different problem (versus just a new instance of the same problem) fixed in https://github.com/candid82/joker/pull/207?

If not, the fix might be limited in scope (haven't checked this myself just yet), and further problems might be avoided by adding a 32-bit-host build to the CI test.

**Comment by jcburley** [comment]
> Is this a different problem (versus just a new instance of the same problem) fixed in #207?
> 
> If not, the fix might be limited in scope (haven't checked this myself just yet), and further problems might be avoided by adding a 32-bit-host build to the CI test.

Ah, having now spent a few minutes looking into this, I see it's a different problem. That earlier PR of mine fixed only internal code; the problem here is the new interface exposed to Joker code, and Joker currently supports only `Int` (Go's `int`, which is 32-bit on 32-bit systems) and `BigInt` (from Go's `big` library), but not a type corresponding to Go's `int64`.

Submitted https://github.com/candid82/joker/pull/244 as one approach to fix this. Been awhile since I've had my head deep into Joker code, so apologies in advance for evident rust or other nonsense.

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/pull/244 Thanks @jcburley!
